### ISSUE TITLE
V1.0 checklist

### ISSUE THREAD

**Issue by yhtang** [yhtang/FunFact#181]
- [x] outstanding issues: #166, #179, #182, #116, #111, #109, #13.
- [x] update `README.md` and `index.md`
- [x] rerun all example notebooks
- [x] check PyPI semver convention
- [x] promotion
